[build]
  publish = "." 
  functions = "netlify/functions"

# توجيه الموافقة على الدفع
[[redirects]]
  from = "/api/pi/approve"
  to = "/.netlify/functions/approve"
  status = 200
  force = true

# توجيه إكمال الدفع
[[redirects]]
  from = "/api/pi/complete"
  to = "/.netlify/functions/complete"
  status = 200
  force = true

  